version: '3.8'

services:
    bot:
        container_name: tg-simple-ytdl
        build:
            context: .
        stop_signal: SIGINT
        restart: on-failure
        env_file: .env
        environment:
            - LOG_LEVEL=warn
            - DISABLE_LOG_TIMESTAMP=false